name: Primeiro Desafio

on: 
  push:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        run: |
          git clone https://github.com/UniFiTyr/Bruh.git
          cd Bruh 
          chmod +x test.sh
          ./test.sh > output.log

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output_log
          path: output.log
