name: Primeiro Desafio

on: 
  push:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        run: |
          git clone https://github.com/UniFiTyr/Bruh.git &&
          cd Bruh
      
      - name: Make it executable
        run: |
          cd Bruh && 
          chmod +x test.sh
      
      - name: Execute it
        run: |
          cd Bruh
          ./test.sh > output.log 2>&1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output_log
          path: output.log
