name: Primeiro Desafio

on: 
  push:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        run: |
          git clone https://github.com/UniFiTyr/-.git

      - name: make it executable
        run: |
          cd -/
          chmod +x test.sh

      - name: execute and save
        run: ./test.sh > output.zip
